### ISSUE TITLE
png

### ISSUE THREAD

**Issue by raphaelkaique1** [Tech-N-Logic/.github#2]
![microchip](https://github.com/user-attachments/assets/62837c66-17e2-47cd-a32f-f329ae10dc04)
![button](https://github.com/user-attachments/assets/ac215517-28f0-4822-ab06-8a9fb5ce2906)
![secure-data](https://github.com/user-attachments/assets/d03045c4-0b5a-457e-bcb0-33c4e663c4ad)
![settings](https://github.com/user-attachments/assets/aedc8148-acc9-47fd-a0b4-c8496181182b)
![atom](https://github.com/user-attachments/assets/8321160a-bf04-4c30-8be0-a5edbf2ef15c)

**Comment by fulltechware** [comment]
```
![microchip](https://github.com/user-attachments/assets/62837c66-17e2-47cd-a32f-f329ae10dc04)
![button](https://github.com/user-attachments/assets/ac215517-28f0-4822-ab06-8a9fb5ce2906)
![secure-data](https://github.com/user-attachments/assets/d03045c4-0b5a-457e-bcb0-33c4e663c4ad)
![settings](https://github.com/user-attachments/assets/aedc8148-acc9-47fd-a0b4-c8496181182b)
![atom](https://github.com/user-attachments/assets/8321160a-bf04-4c30-8be0-a5edbf2ef15c)

```
